### PR TITLE
Automatic build with GitHub Actions

### PR DESCRIPTION
**Pull request by segfault-bilibili**
Note (after merge) : this reverts #4 in 7305f36162a7df2d6e13c4ecdfe411b9e2135dea

--------

### Initial Setup

1. `base64 -w0 < release_signing_key.keystore`
2. Add the base64-encoded keystore file as a Repository secret named `KEYSTORE_BASE64` to [repo action settings](https://github.com/rayshift/magiatranslate/settings/secrets/actions)
3. Add the keystore password (without the `pass:` prefix) as `KS_PASS` (and add `KEY_PASS` and `KS_KEY_ALIAS` as well if needed)
4. Enable actions

### Usage

It automatically build on new official game release, and then do a prerelease.

To do a manual production-ready release:

1. Change `ci_versions/src_apk.sh` and push the change to `master` or `dev` branch to trigger a rebuild from new version of source APK
2. Add a tag like `git tag -s -m "release description" v123` and push it to trigger a release (add a `-prerelease` suffix to do a prerelease)

### CODE REVIEW

**Comment by segfault-bilibili** [comment]
~f9d5aee1645525717d0d71c88ef6d1ed88485bd0 doesn't extract armv7 libs correctly. fixing that.~
```Shell
mv "${BASEDIR}/build/armv7/app/lib/armeabi-v7a/*" "${BASEDIR}/build/app/lib/armeabi-v7a/"
```
~the wildcard `*` should not be quoted.~
fixed

**Comment by segfault-bilibili** [comment]
fixed

**Comment by segfault-bilibili** [comment]
I plan to remove nodejs dependency and fix Dobby for armeabi-v7a instead @neobenedict

**Comment by neobenedict** [comment]
> I plan to remove nodejs dependency and fix Dobby for armeabi-v7a instead @neobenedict

If you figure out the issue, PR the rayshift/dobby repo as well.

**Comment by segfault-bilibili** [comment]
>If you figure out the issue, PR the rayshift/dobby repo as well.

Of course. However I haven't finished the patch/pr for Dobby yet.

**Comment by segfault-bilibili** [comment]
logcat | grep MagiaHook
```
07-08 01:23:58.075  5178  5178 I MagiaHook: Starting MagiaHook.
07-08 01:23:58.077  5178  5210 I MagiaHook: Library location: /data/app/io.kamihama.magiatranslate.experiment-1/lib/arm64/libmadomagi_native.so
07-08 01:23:58.077  5178  5210 I MagiaHook: Base address: 0x4000000
07-08 01:23:58.099  5178  5210 I MagiaHook: Successfully hooked UrlConfig::resource.
07-08 01:23:58.104  5178  5210 I MagiaHook: Successfully hooked SceneLayerManager::createSceneLayer.
07-08 01:23:58.108  5178  5210 I MagiaHook: Successfully hooked http2::Http2Session::setMaxConnectionNum.
07-08 01:23:58.117  5178  5210 I MagiaHook: Successfully hooked criNcv_GetHardwareSamplingRate_ANDROID.
07-08 01:23:58.122  5178  5210 I MagiaHook: Successfully hooked criNcv_SetHardwareSamplingRate_ANDROID.
07-08 01:23:58.128  5178  5210 I MagiaHook: Successfully hooked cocos2d::Node::setPosition.
07-08 01:23:58.140  5178  5210 I MagiaHook: Successfully hooked cocos2d::Label::setMaxLineWidth.
07-08 01:23:58.142  5178  5210 I MagiaHook: Successfully hooked cocos2d::Label::setDimensions.
07-08 01:23:58.152  5178  5210 I MagiaHook: Successfully hooked LbUtility::getViewPosition.
07-08 01:23:58.158  5178  5210 I MagiaHook: Successfully hooked cocos2d::Label::createWithTTF.
07-08 01:23:58.172  5178  5210 I MagiaHook: Exiting hook thread.
07-08 01:23:58.695  5178  5203 I MagiaHook: set cached hardware sample rate to 44100
07-08 01:23:58.704  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:58.704  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:58.706  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:58.706  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:58.706  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:58.706  5178  5203 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:23:59.393  5178  5203 I MagiaHook: Scene layer changed to: StartupSceneLayer
07-08 01:23:59.393  5178  5203 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:24:03.960  5178  5203 I MagiaHook: Scene layer changed to: WebSceneLayer
07-08 01:24:05.080  5178  5203 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:24:05.132  5178  5203 I MagiaHook: Scene layer changed to: LoadingSceneLayer
07-08 01:24:06.474  5178  5203 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:24:07.232  5178  5203 I MagiaHook: Scene layer changed to: TopSceneLayer
```
-------
```
07-08 01:04:14.025  6637  6637 I MagiaHook: Starting MagiaHook.
07-08 01:04:14.026  6637  6676 I MagiaHook: Library location: /data/app/io.kamihama.magiatranslate.experiment-ZkSKdJRAUeSLBmdFrFdO9A==/lib/arm/libmadomagi_native.so
07-08 01:04:14.027  6637  6676 I MagiaHook: Base address: 0x31d0000
07-08 01:04:14.058  6637  6676 I MagiaHook: Successfully hooked UrlConfig::resource.
07-08 01:04:14.067  6637  6676 I MagiaHook: Successfully hooked SceneLayerManager::createSceneLayer.
07-08 01:04:14.079  6637  6676 I MagiaHook: Successfully hooked http2::Http2Session::setMaxConnectionNum.
07-08 01:04:14.089  6637  6676 I MagiaHook: Successfully hooked criNcv_GetHardwareSamplingRate_ANDROID.
07-08 01:04:14.101  6637  6676 I MagiaHook: Successfully hooked criNcv_SetHardwareSamplingRate_ANDROID.
07-08 01:04:14.107  6637  6676 I MagiaHook: Successfully hooked cocos2d::Node::setPosition.
07-08 01:04:14.109  6637  6676 I MagiaHook: Successfully hooked cocos2d::Label::setMaxLineWidth.
07-08 01:04:14.110  6637  6676 I MagiaHook: Successfully hooked cocos2d::Label::setDimensions.
07-08 01:04:14.111  6637  6676 I MagiaHook: Successfully hooked LbUtility::getViewPosition.
07-08 01:04:14.112  6637  6676 I MagiaHook: Successfully hooked cocos2d::Label::createWithTTF.
07-08 01:04:14.115  6637  6676 I MagiaHook: Exiting hook thread.
07-08 01:04:14.767  6637  6667 I MagiaHook: set cached hardware sample rate to 44100
07-08 01:04:14.774  6637  6667 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:04:14.780  6637  6667 I MagiaHook: using hardware sample rate: 48000 (orig: 44100)
07-08 01:04:15.397  6637  6667 I MagiaHook: Scene layer changed to: StartupSceneLayer
07-08 01:04:15.398  6637  6667 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:04:19.427  6637  6667 I MagiaHook: Scene layer changed to: WebSceneLayer
07-08 01:04:20.437  6637  6667 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:04:20.467  6637  6667 I MagiaHook: Scene layer changed to: LoadingSceneLayer
07-08 01:04:21.855  6637  6667 I MagiaHook: Scene layer changed to: TapSceneLayer
07-08 01:04:22.727  6637  6667 I MagiaHook: Scene layer changed to: TopSceneLayer
```

**Comment by segfault-bilibili** [comment]
Actually this commit does not achieve true "automatic" build yet. I think this could be done with another action yml which runs regularly with `schedule` trigger, checking the `ready.txt` on rikaren.

**Comment by segfault-bilibili** [comment]
@neobenedict you may merge this first, and then I will submit another PR to periodically check new version & truly automate building afterwards.

**Comment by segfault-bilibili** [comment]
It's probably better to avoid relying on rikaren as well. However this obviously requires some more work. A google account also seems to be required.

**Comment by segfault-bilibili** [comment]
okay now it really automatically builds

**Pull request merged**
